namespace FundingPlatform.Contracts.Projects;

public sealed record ProjectSummaryResponse(
    Guid PublicId,
    string Slug,
    string Title,
    string? Summary,
    byte Status,
    byte? ProjectStage,
    byte PublicationStatus,
    DateOnly? StartDate,
    DateOnly? EndDate,
    decimal? BudgetTotal,
    decimal? ConfirmedFunding,
    string? Currency,
    decimal? FundingGap,
    int ProjectVersion,
    DateTimeOffset UpdatedAtUtc);

public sealed record ProjectResponse(
    Guid PublicId,
    string Slug,
    string Title,
    string? Summary,
    string? Description,
    byte Status,
    byte? ProjectStage,
    byte PublicationStatus,
    DateOnly? StartDate,
    DateOnly? EndDate,
    decimal? BudgetTotal,
    decimal? ConfirmedFunding,
    string? Currency,
    decimal? FundingGap,
    int ProjectVersion,
    DateTimeOffset UpdatedAtUtc,
    string ETag,
    IReadOnlyList<short> CountryIds,
    IReadOnlyList<int> RegionIds,
    IReadOnlyList<int> CategoryIds,
    IReadOnlyList<int> BeneficiaryTypeIds,
    IReadOnlyList<int> ProjectTypeIds,
    IReadOnlyList<int> SustainableDevelopmentGoalIds,
    DateTimeOffset? SubmittedAtUtc,
    DateTimeOffset? ReviewedAtUtc,
    string? RejectionReason,
    DateTimeOffset? PublishedAtUtc,
    ProjectEnrichmentContract? Enrichment = null);

public sealed record ProjectWriteRequest(
    string Title,
    string? Summary,
    string? Description,
    byte Status,
    DateOnly? StartDate,
    DateOnly? EndDate,
    decimal? BudgetTotal,
    decimal? ConfirmedFunding,
    string? Currency,
    IReadOnlyList<short>? CountryIds,
    IReadOnlyList<int>? RegionIds,
    IReadOnlyList<int>? CategoryIds,
    IReadOnlyList<int>? BeneficiaryTypeIds,
    IReadOnlyList<int>? ProjectTypeIds,
    IReadOnlyList<int>? SustainableDevelopmentGoalIds = null,
    byte? ProjectStage = null,
    ProjectEnrichmentContract? Enrichment = null);

public sealed record ProjectCreatedResponse(Guid PublicId, int ProjectVersion, string ETag);
