<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../FundingPlatform.Application/FundingPlatform.Application.csproj" />
    <ProjectReference Include="../FundingPlatform.Core/FundingPlatform.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" />
  </ItemGroup>

</Project>
