/* FundingPlatform - worldwide country catalog.
   Forward-only data migration; the migrator owns the transaction.
   Source snapshot: 2026-09-12, UN M49 (248 ISO-coded countries/areas) plus
   ISO TW/158/TWN. See docs/WORLD-COUNTRY-CATALOG.md for source provenance.
   Preserve existing identifiers, labels, timestamps and inactive choices.
   No regions, geographic eligibility, funders or account records are changed.
*/
SET NOCOUNT ON;
SET XACT_ABORT ON;

IF OBJECT_ID(N'dbo.FundingPlatform_Countries', N'U') IS NULL
    THROW 55580, N'Country catalog requires migration 001.', 1;

DECLARE @Countries TABLE
(
    Id SMALLINT NOT NULL PRIMARY KEY,
    Iso2 CHAR(2) NOT NULL UNIQUE,
    Iso3 CHAR(3) NOT NULL UNIQUE,
    Name NVARCHAR(120) NOT NULL
);

INSERT INTO @Countries (Id, Iso2, Iso3, Name)
VALUES
    (4, 'AF', 'AFG', N'Afganistán'),
    (8, 'AL', 'ALB', N'Albania'),
    (10, 'AQ', 'ATA', N'Antártida'),
    (12, 'DZ', 'DZA', N'Argelia'),
    (16, 'AS', 'ASM', N'Samoa Americana'),
    (20, 'AD', 'AND', N'Andorra'),
    (24, 'AO', 'AGO', N'Angola'),
    (28, 'AG', 'ATG', N'Antigua y Barbuda'),
    (31, 'AZ', 'AZE', N'Azerbaiyán'),
    (32, 'AR', 'ARG', N'Argentina'),
    (36, 'AU', 'AUS', N'Australia'),
    (40, 'AT', 'AUT', N'Austria'),
    (44, 'BS', 'BHS', N'Bahamas'),
    (48, 'BH', 'BHR', N'Bahrein'),
    (50, 'BD', 'BGD', N'Bangladesh'),
    (51, 'AM', 'ARM', N'Armenia'),
    (52, 'BB', 'BRB', N'Barbados'),
    (56, 'BE', 'BEL', N'Bélgica'),
    (60, 'BM', 'BMU', N'Bermuda'),
    (64, 'BT', 'BTN', N'Bhután'),
    (68, 'BO', 'BOL', N'Bolivia (Estado Plurinacional de)'),
    (70, 'BA', 'BIH', N'Bosnia y Herzegovina'),
    (72, 'BW', 'BWA', N'Botswana'),
    (74, 'BV', 'BVT', N'Isla Bouvet'),
    (76, 'BR', 'BRA', N'Brasil'),
    (84, 'BZ', 'BLZ', N'Belice'),
    (86, 'IO', 'IOT', N'Territorio Británico del Océano Índico'),
    (90, 'SB', 'SLB', N'Islas Salomón'),
    (92, 'VG', 'VGB', N'Islas Vírgenes Británicas'),
    (96, 'BN', 'BRN', N'Brunei Darussalam'),
    (100, 'BG', 'BGR', N'Bulgaria'),
    (104, 'MM', 'MMR', N'Myanmar'),
    (108, 'BI', 'BDI', N'Burundi'),
    (112, 'BY', 'BLR', N'Belarús'),
    (116, 'KH', 'KHM', N'Camboya'),
    (120, 'CM', 'CMR', N'Camerún'),
    (124, 'CA', 'CAN', N'Canadá'),
    (132, 'CV', 'CPV', N'Cabo Verde'),
    (136, 'KY', 'CYM', N'Islas Caimán'),
    (140, 'CF', 'CAF', N'República Centroafricana'),
    (144, 'LK', 'LKA', N'Sri Lanka'),
    (148, 'TD', 'TCD', N'Chad'),
    (152, 'CL', 'CHL', N'Chile'),
    (156, 'CN', 'CHN', N'China'),
    (158, 'TW', 'TWN', N'Taiwán'),
    (162, 'CX', 'CXR', N'Isla Christmas'),
    (166, 'CC', 'CCK', N'Islas Cocos (Keeling)'),
    (170, 'CO', 'COL', N'Colombia'),
    (174, 'KM', 'COM', N'Comoras'),
    (175, 'YT', 'MYT', N'Mayotte'),
    (178, 'CG', 'COG', N'Congo'),
    (180, 'CD', 'COD', N'República Democrática del Congo'),
    (184, 'CK', 'COK', N'Islas Cook'),
    (188, 'CR', 'CRI', N'Costa Rica'),
    (191, 'HR', 'HRV', N'Croacia'),
    (192, 'CU', 'CUB', N'Cuba'),
    (196, 'CY', 'CYP', N'Chipre'),
    (203, 'CZ', 'CZE', N'Chequia'),
    (204, 'BJ', 'BEN', N'Benin'),
    (208, 'DK', 'DNK', N'Dinamarca'),
    (212, 'DM', 'DMA', N'Dominica'),
    (214, 'DO', 'DOM', N'República Dominicana'),
    (218, 'EC', 'ECU', N'Ecuador'),
    (222, 'SV', 'SLV', N'El Salvador'),
    (226, 'GQ', 'GNQ', N'Guinea Ecuatorial'),
    (231, 'ET', 'ETH', N'Etiopía'),
    (232, 'ER', 'ERI', N'Eritrea'),
    (233, 'EE', 'EST', N'Estonia'),
    (234, 'FO', 'FRO', N'Islas Feroe'),
    (238, 'FK', 'FLK', N'Islas Malvinas (Falkland)'),
    (239, 'GS', 'SGS', N'Georgia del Sur y las Islas Sandwich del Sur'),
    (242, 'FJ', 'FJI', N'Fiji'),
    (246, 'FI', 'FIN', N'Finlandia'),
    (248, 'AX', 'ALA', N'Islas Åland'),
    (250, 'FR', 'FRA', N'Francia'),
    (254, 'GF', 'GUF', N'Guayana Francesa'),
    (258, 'PF', 'PYF', N'Polinesia Francesa'),
    (260, 'TF', 'ATF', N'Territorio de las Tierras Australes Francesas'),
    (262, 'DJ', 'DJI', N'Djibouti'),
    (266, 'GA', 'GAB', N'Gabón'),
    (268, 'GE', 'GEO', N'Georgia'),
    (270, 'GM', 'GMB', N'Gambia'),
    (275, 'PS', 'PSE', N'Estado de Palestina'),
    (276, 'DE', 'DEU', N'Alemania'),
    (288, 'GH', 'GHA', N'Ghana'),
    (292, 'GI', 'GIB', N'Gibraltar'),
    (296, 'KI', 'KIR', N'Kiribati'),
    (300, 'GR', 'GRC', N'Grecia'),
    (304, 'GL', 'GRL', N'Groenlandia'),
    (308, 'GD', 'GRD', N'Granada'),
    (312, 'GP', 'GLP', N'Guadalupe'),
    (316, 'GU', 'GUM', N'Guam'),
    (320, 'GT', 'GTM', N'Guatemala'),
    (324, 'GN', 'GIN', N'Guinea'),
    (328, 'GY', 'GUY', N'Guyana'),
    (332, 'HT', 'HTI', N'Haití'),
    (334, 'HM', 'HMD', N'Islas Heard y McDonald'),
    (336, 'VA', 'VAT', N'Santa Sede'),
    (340, 'HN', 'HND', N'Honduras'),
    (344, 'HK', 'HKG', N'China, región administrativa especial de Hong Kong'),
    (348, 'HU', 'HUN', N'Hungría'),
    (352, 'IS', 'ISL', N'Islandia'),
    (356, 'IN', 'IND', N'India'),
    (360, 'ID', 'IDN', N'Indonesia'),
    (364, 'IR', 'IRN', N'Irán (República Islámica del)'),
    (368, 'IQ', 'IRQ', N'Iraq'),
    (372, 'IE', 'IRL', N'Irlanda'),
    (376, 'IL', 'ISR', N'Israel'),
    (380, 'IT', 'ITA', N'Italia'),
    (384, 'CI', 'CIV', N'Côte d’Ivoire'),
    (388, 'JM', 'JAM', N'Jamaica'),
    (392, 'JP', 'JPN', N'Japón'),
    (398, 'KZ', 'KAZ', N'Kazajstán'),
    (400, 'JO', 'JOR', N'Jordania'),
    (404, 'KE', 'KEN', N'Kenya'),
    (408, 'KP', 'PRK', N'República Popular Democrática de Corea'),
    (410, 'KR', 'KOR', N'República de Corea'),
    (414, 'KW', 'KWT', N'Kuwait'),
    (417, 'KG', 'KGZ', N'Kirguistán'),
    (418, 'LA', 'LAO', N'República Democrática Popular Lao'),
    (422, 'LB', 'LBN', N'Líbano'),
    (426, 'LS', 'LSO', N'Lesotho'),
    (428, 'LV', 'LVA', N'Letonia'),
    (430, 'LR', 'LBR', N'Liberia'),
    (434, 'LY', 'LBY', N'Libia'),
    (438, 'LI', 'LIE', N'Liechtenstein'),
    (440, 'LT', 'LTU', N'Lituania'),
    (442, 'LU', 'LUX', N'Luxemburgo'),
    (446, 'MO', 'MAC', N'China, región administrativa especial de Macao'),
    (450, 'MG', 'MDG', N'Madagascar'),
    (454, 'MW', 'MWI', N'Malawi'),
    (458, 'MY', 'MYS', N'Malasia'),
    (462, 'MV', 'MDV', N'Maldivas'),
    (466, 'ML', 'MLI', N'Malí'),
    (470, 'MT', 'MLT', N'Malta'),
    (474, 'MQ', 'MTQ', N'Martinica'),
    (478, 'MR', 'MRT', N'Mauritania'),
    (480, 'MU', 'MUS', N'Mauricio'),
    (484, 'MX', 'MEX', N'México'),
    (492, 'MC', 'MCO', N'Mónaco'),
    (496, 'MN', 'MNG', N'Mongolia'),
    (498, 'MD', 'MDA', N'República de Moldova'),
    (499, 'ME', 'MNE', N'Montenegro'),
    (500, 'MS', 'MSR', N'Montserrat'),
    (504, 'MA', 'MAR', N'Marruecos'),
    (508, 'MZ', 'MOZ', N'Mozambique'),
    (512, 'OM', 'OMN', N'Omán'),
    (516, 'NA', 'NAM', N'Namibia'),
    (520, 'NR', 'NRU', N'Naoero'),
    (524, 'NP', 'NPL', N'Nepal'),
    (528, 'NL', 'NLD', N'Países Bajos (Reino de los)'),
    (531, 'CW', 'CUW', N'Curazao'),
    (533, 'AW', 'ABW', N'Aruba'),
    (534, 'SX', 'SXM', N'San Martín (parte Holandesa)'),
    (535, 'BQ', 'BES', N'Bonaire, San Eustaquio y Saba'),
    (540, 'NC', 'NCL', N'Nueva Caledonia'),
    (548, 'VU', 'VUT', N'Vanuatu'),
    (554, 'NZ', 'NZL', N'Nueva Zelandia'),
    (558, 'NI', 'NIC', N'Nicaragua'),
    (562, 'NE', 'NER', N'Níger'),
    (566, 'NG', 'NGA', N'Nigeria'),
    (570, 'NU', 'NIU', N'Niue'),
    (574, 'NF', 'NFK', N'Isla Norfolk'),
    (578, 'NO', 'NOR', N'Noruega'),
    (580, 'MP', 'MNP', N'Islas Marianas Septentrionales'),
    (581, 'UM', 'UMI', N'Islas menores alejadas de Estados Unidos'),
    (583, 'FM', 'FSM', N'Micronesia (Estados Federados de)'),
    (584, 'MH', 'MHL', N'Islas Marshall'),
    (585, 'PW', 'PLW', N'Palau'),
    (586, 'PK', 'PAK', N'Pakistán'),
    (591, 'PA', 'PAN', N'Panamá'),
    (598, 'PG', 'PNG', N'Papua Nueva Guinea'),
    (600, 'PY', 'PRY', N'Paraguay'),
    (604, 'PE', 'PER', N'Perú'),
    (608, 'PH', 'PHL', N'Filipinas'),
    (612, 'PN', 'PCN', N'Pitcairn'),
    (616, 'PL', 'POL', N'Polonia'),
    (620, 'PT', 'PRT', N'Portugal'),
    (624, 'GW', 'GNB', N'Guinea-Bissau'),
    (626, 'TL', 'TLS', N'Timor-Leste'),
    (630, 'PR', 'PRI', N'Puerto Rico'),
    (634, 'QA', 'QAT', N'Qatar'),
    (638, 'RE', 'REU', N'Reunión'),
    (642, 'RO', 'ROU', N'Rumania'),
    (643, 'RU', 'RUS', N'Federación de Rusia'),
    (646, 'RW', 'RWA', N'Rwanda'),
    (652, 'BL', 'BLM', N'San Barthélemy'),
    (654, 'SH', 'SHN', N'Santa Elena'),
    (659, 'KN', 'KNA', N'Saint Kitts y Nevis'),
    (660, 'AI', 'AIA', N'Anguila'),
    (662, 'LC', 'LCA', N'Santa Lucía'),
    (663, 'MF', 'MAF', N'San Martín (parte francesa)'),
    (666, 'PM', 'SPM', N'San Pedro y Miquelón'),
    (670, 'VC', 'VCT', N'San Vicente y las Granadinas'),
    (674, 'SM', 'SMR', N'San Marino'),
    (678, 'ST', 'STP', N'Santo Tomé y Príncipe'),
    (682, 'SA', 'SAU', N'Arabia Saudita'),
    (686, 'SN', 'SEN', N'Senegal'),
    (688, 'RS', 'SRB', N'Serbia'),
    (690, 'SC', 'SYC', N'Seychelles'),
    (694, 'SL', 'SLE', N'Sierra Leona'),
    (702, 'SG', 'SGP', N'Singapur'),
    (703, 'SK', 'SVK', N'Eslovaquia'),
    (704, 'VN', 'VNM', N'Viet Nam'),
    (705, 'SI', 'SVN', N'Eslovenia'),
    (706, 'SO', 'SOM', N'Somalia'),
    (710, 'ZA', 'ZAF', N'Sudáfrica'),
    (716, 'ZW', 'ZWE', N'Zimbabwe'),
    (724, 'ES', 'ESP', N'España'),
    (728, 'SS', 'SSD', N'Sudán del Sur'),
    (729, 'SD', 'SDN', N'Sudán'),
    (732, 'EH', 'ESH', N'Sáhara Occidental'),
    (740, 'SR', 'SUR', N'Suriname'),
    (744, 'SJ', 'SJM', N'Islas Svalbard y Jan Mayen'),
    (748, 'SZ', 'SWZ', N'Eswatini'),
    (752, 'SE', 'SWE', N'Suecia'),
    (756, 'CH', 'CHE', N'Suiza'),
    (760, 'SY', 'SYR', N'República Árabe Siria'),
    (762, 'TJ', 'TJK', N'Tayikistán'),
    (764, 'TH', 'THA', N'Tailandia'),
    (768, 'TG', 'TGO', N'Togo'),
    (772, 'TK', 'TKL', N'Tokelau'),
    (776, 'TO', 'TON', N'Tonga'),
    (780, 'TT', 'TTO', N'Trinidad y Tabago'),
    (784, 'AE', 'ARE', N'Emiratos Árabes Unidos'),
    (788, 'TN', 'TUN', N'Túnez'),
    (792, 'TR', 'TUR', N'Türkiye'),
    (795, 'TM', 'TKM', N'Turkmenistán'),
    (796, 'TC', 'TCA', N'Islas Turcas y Caicos'),
    (798, 'TV', 'TUV', N'Tuvalu'),
    (800, 'UG', 'UGA', N'Uganda'),
    (804, 'UA', 'UKR', N'Ucrania'),
    (807, 'MK', 'MKD', N'Macedonia del Norte'),
    (818, 'EG', 'EGY', N'Egipto'),
    (826, 'GB', 'GBR', N'Reino Unido de Gran Bretaña e Irlanda del Norte'),
    (831, 'GG', 'GGY', N'Guernsey'),
    (832, 'JE', 'JEY', N'Jersey'),
    (833, 'IM', 'IMN', N'Isla de Man'),
    (834, 'TZ', 'TZA', N'República Unida de Tanzanía'),
    (840, 'US', 'USA', N'Estados Unidos de América'),
    (850, 'VI', 'VIR', N'Islas Vírgenes de los Estados Unidos'),
    (854, 'BF', 'BFA', N'Burkina Faso'),
    (858, 'UY', 'URY', N'Uruguay'),
    (860, 'UZ', 'UZB', N'Uzbekistán'),
    (862, 'VE', 'VEN', N'Venezuela (República Bolivariana de)'),
    (876, 'WF', 'WLF', N'Islas Wallis y Futuna'),
    (882, 'WS', 'WSM', N'Samoa'),
    (887, 'YE', 'YEM', N'Yemen'),
    (894, 'ZM', 'ZMB', N'Zambia');

IF (SELECT COUNT(*) FROM @Countries) <> 249
    THROW 55581, N'Worldwide country seed is incomplete.', 1;

/* Fail closed instead of silently re-keying an existing country or reference. */
IF EXISTS
(
    SELECT 1
    FROM @Countries AS Seed
    INNER JOIN dbo.FundingPlatform_Countries AS Existing
        ON Existing.Id = Seed.Id OR Existing.Iso2 = Seed.Iso2 OR Existing.Iso3 = Seed.Iso3
    WHERE Existing.Id <> Seed.Id OR Existing.Iso2 <> Seed.Iso2 OR Existing.Iso3 <> Seed.Iso3
)
    THROW 55582, N'Country identifier or ISO code collision; review existing data before retrying.', 1;

INSERT INTO dbo.FundingPlatform_Countries (Id, Iso2, Iso3, Name)
SELECT Seed.Id, Seed.Iso2, Seed.Iso3, Seed.Name
FROM @Countries AS Seed
WHERE NOT EXISTS
(
    SELECT 1 FROM dbo.FundingPlatform_Countries AS Existing WHERE Existing.Id = Seed.Id
);

/* Existing inactive records remain inactive; do not override deliberate catalog moderation. */
IF EXISTS
(
    SELECT 1 FROM @Countries AS Seed
    LEFT JOIN dbo.FundingPlatform_Countries AS Existing ON Existing.Id = Seed.Id
    WHERE Existing.Id IS NULL OR Existing.Iso2 <> Seed.Iso2 OR Existing.Iso3 <> Seed.Iso3
)
    THROW 55583, N'Worldwide country catalog identities are inconsistent.', 1;
