<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../FundingPlatform.Contracts/FundingPlatform.Contracts.csproj" />
    <ProjectReference Include="../FundingPlatform.Core/FundingPlatform.Core.csproj" />
  </ItemGroup>

</Project>
