namespace FundingPlatform.Contracts.FundingOpportunities;

public sealed record WorkspaceFundingOpportunityListResponse(
    IReadOnlyList<WorkspaceFundingOpportunityListItemResponse> Items,
    long TotalCount,
    int PageNumber,
    int PageSize,
    string SearchMode);

public sealed record WorkspaceFundingOpportunityListItemResponse(
    Guid PublicId,
    string Slug,
    string Title,
    string? Summary,
    string SponsorName,
    string? Currency,
    decimal? MinimumAmount,
    decimal? MaximumAmount,
    DateOnly? OpenDate,
    DateOnly? CloseDate,
    DateTimeOffset? CloseAtUtc,
    byte DeadlineType,
    byte DeadlinePrecision,
    DateTimeOffset PublishedAtUtc,
    decimal DataQualityScore,
    Guid PrimaryFunderPublicId,
    string PrimaryFunderName,
    string SourceName,
    string SourceUrl,
    bool IsFavorite);

public sealed record FundingOpportunityEligibilityTypeResponse(
    short Id,
    byte EligibilityMode);

public sealed record FundingOpportunityLanguageResponse(
    short Id,
    byte LanguagePurpose);

public sealed record WorkspaceFundingOpportunitySourceResponse(
    int FundingSourceId,
    string SourceName,
    string? ExternalId,
    string SourceUrl,
    DateTimeOffset FirstSeenAtUtc,
    DateTimeOffset LastSeenAtUtc,
    bool IsPrimary,
    bool IsActive);

public sealed record WorkspaceFundingOpportunityDetailResponse(
    Guid PublicId,
    string Slug,
    string Title,
    string? Description,
    string? Summary,
    string SponsorName,
    string? SponsorUrl,
    string? ApplicationUrl,
    short? IssuerCountryId,
    short? FundingTypeId,
    string? Currency,
    decimal? MinimumAmount,
    decimal? MaximumAmount,
    byte AmountStatus,
    DateOnly? OpenDate,
    DateOnly? CloseDate,
    DateTimeOffset? CloseAtUtc,
    string? DeadlineTimeZoneId,
    byte DeadlineType,
    byte DeadlinePrecision,
    string? EligibilityDescription,
    string? Requirements,
    string? Objectives,
    string? AllowedActivities,
    string? ExcludedActivities,
    string? Restrictions,
    string? TargetOrganizationsDescription,
    string? TargetPopulationsDescription,
    short? MinimumOperatingYears,
    bool? RequiresLegalEntity,
    bool? RequiresPriorExperience,
    bool? RequiresCofunding,
    decimal? CofundingPercentage,
    byte GeographicScope,
    byte RemoteApplication,
    DateTimeOffset LastVerifiedAtUtc,
    decimal DataQualityScore,
    int ContentVersion,
    DateTimeOffset PublishedAtUtc,
    Guid PrimaryFunderPublicId,
    string PrimaryFunderSlug,
    string PrimaryFunderName,
    string SourceName,
    string SourceUrl,
    string? ExternalId,
    bool IsFavorite,
    IReadOnlyList<short> CountryIds,
    IReadOnlyList<int> RegionIds,
    IReadOnlyList<int> CategoryIds,
    IReadOnlyList<int> BeneficiaryTypeIds,
    IReadOnlyList<int> ProjectTypeIds,
    IReadOnlyList<long> TagIds,
    IReadOnlyList<FundingOpportunityEligibilityTypeResponse> OrganizationTypes,
    IReadOnlyList<FundingOpportunityEligibilityTypeResponse> LegalEntityTypes,
    IReadOnlyList<FundingOpportunityLanguageResponse> Languages,
    IReadOnlyList<FundingOpportunityFunderResponse> Funders,
    IReadOnlyList<WorkspaceFundingOpportunitySourceResponse> Sources);
