/* Worldwide countries and funder persistence; synthetic fixtures, rollback only.
   Requires migration 048 on disposable/dev SQL. Parsing is not SQL execution. */
SET NOCOUNT ON;
SET XACT_ABORT OFF;

DECLARE @ExpectedCountries TABLE (Id SMALLINT PRIMARY KEY, Iso2 CHAR(2), Iso3 CHAR(3));
INSERT INTO @ExpectedCountries (Id, Iso2, Iso3)
VALUES
    (4, 'AF', 'AFG'),
    (8, 'AL', 'ALB'),
    (10, 'AQ', 'ATA'),
    (12, 'DZ', 'DZA'),
    (16, 'AS', 'ASM'),
    (20, 'AD', 'AND'),
    (24, 'AO', 'AGO'),
    (28, 'AG', 'ATG'),
    (31, 'AZ', 'AZE'),
    (32, 'AR', 'ARG'),
    (36, 'AU', 'AUS'),
    (40, 'AT', 'AUT'),
    (44, 'BS', 'BHS'),
    (48, 'BH', 'BHR'),
    (50, 'BD', 'BGD'),
    (51, 'AM', 'ARM'),
    (52, 'BB', 'BRB'),
    (56, 'BE', 'BEL'),
    (60, 'BM', 'BMU'),
    (64, 'BT', 'BTN'),
    (68, 'BO', 'BOL'),
    (70, 'BA', 'BIH'),
    (72, 'BW', 'BWA'),
    (74, 'BV', 'BVT'),
    (76, 'BR', 'BRA'),
    (84, 'BZ', 'BLZ'),
    (86, 'IO', 'IOT'),
    (90, 'SB', 'SLB'),
    (92, 'VG', 'VGB'),
    (96, 'BN', 'BRN'),
    (100, 'BG', 'BGR'),
    (104, 'MM', 'MMR'),
    (108, 'BI', 'BDI'),
    (112, 'BY', 'BLR'),
    (116, 'KH', 'KHM'),
    (120, 'CM', 'CMR'),
    (124, 'CA', 'CAN'),
    (132, 'CV', 'CPV'),
    (136, 'KY', 'CYM'),
    (140, 'CF', 'CAF'),
    (144, 'LK', 'LKA'),
    (148, 'TD', 'TCD'),
    (152, 'CL', 'CHL'),
    (156, 'CN', 'CHN'),
    (158, 'TW', 'TWN'),
    (162, 'CX', 'CXR'),
    (166, 'CC', 'CCK'),
    (170, 'CO', 'COL'),
    (174, 'KM', 'COM'),
    (175, 'YT', 'MYT'),
    (178, 'CG', 'COG'),
    (180, 'CD', 'COD'),
    (184, 'CK', 'COK'),
    (188, 'CR', 'CRI'),
    (191, 'HR', 'HRV'),
    (192, 'CU', 'CUB'),
    (196, 'CY', 'CYP'),
    (203, 'CZ', 'CZE'),
    (204, 'BJ', 'BEN'),
    (208, 'DK', 'DNK'),
    (212, 'DM', 'DMA'),
    (214, 'DO', 'DOM'),
    (218, 'EC', 'ECU'),
    (222, 'SV', 'SLV'),
    (226, 'GQ', 'GNQ'),
    (231, 'ET', 'ETH'),
    (232, 'ER', 'ERI'),
    (233, 'EE', 'EST'),
    (234, 'FO', 'FRO'),
    (238, 'FK', 'FLK'),
    (239, 'GS', 'SGS'),
    (242, 'FJ', 'FJI'),
    (246, 'FI', 'FIN'),
    (248, 'AX', 'ALA'),
    (250, 'FR', 'FRA'),
    (254, 'GF', 'GUF'),
    (258, 'PF', 'PYF'),
    (260, 'TF', 'ATF'),
    (262, 'DJ', 'DJI'),
    (266, 'GA', 'GAB'),
    (268, 'GE', 'GEO'),
    (270, 'GM', 'GMB'),
    (275, 'PS', 'PSE'),
    (276, 'DE', 'DEU'),
    (288, 'GH', 'GHA'),
    (292, 'GI', 'GIB'),
    (296, 'KI', 'KIR'),
    (300, 'GR', 'GRC'),
    (304, 'GL', 'GRL'),
    (308, 'GD', 'GRD'),
    (312, 'GP', 'GLP'),
    (316, 'GU', 'GUM'),
    (320, 'GT', 'GTM'),
    (324, 'GN', 'GIN'),
    (328, 'GY', 'GUY'),
    (332, 'HT', 'HTI'),
    (334, 'HM', 'HMD'),
    (336, 'VA', 'VAT'),
    (340, 'HN', 'HND'),
    (344, 'HK', 'HKG'),
    (348, 'HU', 'HUN'),
    (352, 'IS', 'ISL'),
    (356, 'IN', 'IND'),
    (360, 'ID', 'IDN'),
    (364, 'IR', 'IRN'),
    (368, 'IQ', 'IRQ'),
    (372, 'IE', 'IRL'),
    (376, 'IL', 'ISR'),
    (380, 'IT', 'ITA'),
    (384, 'CI', 'CIV'),
    (388, 'JM', 'JAM'),
    (392, 'JP', 'JPN'),
    (398, 'KZ', 'KAZ'),
    (400, 'JO', 'JOR'),
    (404, 'KE', 'KEN'),
    (408, 'KP', 'PRK'),
    (410, 'KR', 'KOR'),
    (414, 'KW', 'KWT'),
    (417, 'KG', 'KGZ'),
    (418, 'LA', 'LAO'),
    (422, 'LB', 'LBN'),
    (426, 'LS', 'LSO'),
    (428, 'LV', 'LVA'),
    (430, 'LR', 'LBR'),
    (434, 'LY', 'LBY'),
    (438, 'LI', 'LIE'),
    (440, 'LT', 'LTU'),
    (442, 'LU', 'LUX'),
    (446, 'MO', 'MAC'),
    (450, 'MG', 'MDG'),
    (454, 'MW', 'MWI'),
    (458, 'MY', 'MYS'),
    (462, 'MV', 'MDV'),
    (466, 'ML', 'MLI'),
    (470, 'MT', 'MLT'),
    (474, 'MQ', 'MTQ'),
    (478, 'MR', 'MRT'),
    (480, 'MU', 'MUS'),
    (484, 'MX', 'MEX'),
    (492, 'MC', 'MCO'),
    (496, 'MN', 'MNG'),
    (498, 'MD', 'MDA'),
    (499, 'ME', 'MNE'),
    (500, 'MS', 'MSR'),
    (504, 'MA', 'MAR'),
    (508, 'MZ', 'MOZ'),
    (512, 'OM', 'OMN'),
    (516, 'NA', 'NAM'),
    (520, 'NR', 'NRU'),
    (524, 'NP', 'NPL'),
    (528, 'NL', 'NLD'),
    (531, 'CW', 'CUW'),
    (533, 'AW', 'ABW'),
    (534, 'SX', 'SXM'),
    (535, 'BQ', 'BES'),
    (540, 'NC', 'NCL'),
    (548, 'VU', 'VUT'),
    (554, 'NZ', 'NZL'),
    (558, 'NI', 'NIC'),
    (562, 'NE', 'NER'),
    (566, 'NG', 'NGA'),
    (570, 'NU', 'NIU'),
    (574, 'NF', 'NFK'),
    (578, 'NO', 'NOR'),
    (580, 'MP', 'MNP'),
    (581, 'UM', 'UMI'),
    (583, 'FM', 'FSM'),
    (584, 'MH', 'MHL'),
    (585, 'PW', 'PLW'),
    (586, 'PK', 'PAK'),
    (591, 'PA', 'PAN'),
    (598, 'PG', 'PNG'),
    (600, 'PY', 'PRY'),
    (604, 'PE', 'PER'),
    (608, 'PH', 'PHL'),
    (612, 'PN', 'PCN'),
    (616, 'PL', 'POL'),
    (620, 'PT', 'PRT'),
    (624, 'GW', 'GNB'),
    (626, 'TL', 'TLS'),
    (630, 'PR', 'PRI'),
    (634, 'QA', 'QAT'),
    (638, 'RE', 'REU'),
    (642, 'RO', 'ROU'),
    (643, 'RU', 'RUS'),
    (646, 'RW', 'RWA'),
    (652, 'BL', 'BLM'),
    (654, 'SH', 'SHN'),
    (659, 'KN', 'KNA'),
    (660, 'AI', 'AIA'),
    (662, 'LC', 'LCA'),
    (663, 'MF', 'MAF'),
    (666, 'PM', 'SPM'),
    (670, 'VC', 'VCT'),
    (674, 'SM', 'SMR'),
    (678, 'ST', 'STP'),
    (682, 'SA', 'SAU'),
    (686, 'SN', 'SEN'),
    (688, 'RS', 'SRB'),
    (690, 'SC', 'SYC'),
    (694, 'SL', 'SLE'),
    (702, 'SG', 'SGP'),
    (703, 'SK', 'SVK'),
    (704, 'VN', 'VNM'),
    (705, 'SI', 'SVN'),
    (706, 'SO', 'SOM'),
    (710, 'ZA', 'ZAF'),
    (716, 'ZW', 'ZWE'),
    (724, 'ES', 'ESP'),
    (728, 'SS', 'SSD'),
    (729, 'SD', 'SDN'),
    (732, 'EH', 'ESH'),
    (740, 'SR', 'SUR'),
    (744, 'SJ', 'SJM'),
    (748, 'SZ', 'SWZ'),
    (752, 'SE', 'SWE'),
    (756, 'CH', 'CHE'),
    (760, 'SY', 'SYR'),
    (762, 'TJ', 'TJK'),
    (764, 'TH', 'THA'),
    (768, 'TG', 'TGO'),
    (772, 'TK', 'TKL'),
    (776, 'TO', 'TON'),
    (780, 'TT', 'TTO'),
    (784, 'AE', 'ARE'),
    (788, 'TN', 'TUN'),
    (792, 'TR', 'TUR'),
    (795, 'TM', 'TKM'),
    (796, 'TC', 'TCA'),
    (798, 'TV', 'TUV'),
    (800, 'UG', 'UGA'),
    (804, 'UA', 'UKR'),
    (807, 'MK', 'MKD'),
    (818, 'EG', 'EGY'),
    (826, 'GB', 'GBR'),
    (831, 'GG', 'GGY'),
    (832, 'JE', 'JEY'),
    (833, 'IM', 'IMN'),
    (834, 'TZ', 'TZA'),
    (840, 'US', 'USA'),
    (850, 'VI', 'VIR'),
    (854, 'BF', 'BFA'),
    (858, 'UY', 'URY'),
    (860, 'UZ', 'UZB'),
    (862, 'VE', 'VEN'),
    (876, 'WF', 'WLF'),
    (882, 'WS', 'WSM'),
    (887, 'YE', 'YEM'),
    (894, 'ZM', 'ZMB');

IF EXISTS
(
    SELECT 1 FROM @ExpectedCountries AS Expected
    LEFT JOIN dbo.FundingPlatform_Countries AS Actual ON Actual.Id = Expected.Id
    WHERE Actual.Id IS NULL OR Actual.Iso2 <> Expected.Iso2 OR Actual.Iso3 <> Expected.Iso3
)
    THROW 55584, N'Worldwide country catalog is incomplete or incorrectly keyed.', 1;

DECLARE @InitialTransactionCount INT = @@TRANCOUNT;
IF @InitialTransactionCount = 0 BEGIN TRANSACTION;
ELSE SAVE TRANSACTION FP_Smoke048;
BEGIN TRY
    DECLARE @Owner UNIQUEIDENTIFIER = NEWID();
    DECLARE @Slug NVARCHAR(180) = N'country-smoke-' + CONVERT(NVARCHAR(36), @Owner);
    DECLARE @Email NVARCHAR(320) = @Slug + N'@example.invalid';
    INSERT INTO dbo.FundingPlatform_Users
        (PublicId, Email, NormalizedEmail, DisplayName, PasswordHash, SecurityStamp, EmailConfirmed, Status, PreferredLocale)
    VALUES (@Owner, @Email, UPPER(@Email), N'Country smoke owner', N'not-a-credential', N'country-smoke', 1, 2, N'es-CL');

    DECLARE @Key BINARY(32) = HASHBYTES('SHA2_256', @Slug + N'-create');
    DECLARE @Hash BINARY(32) = HASHBYTES('SHA2_256', @Slug);
    DECLARE @Result TABLE
        (Succeeded BIT, Code NVARCHAR(50), FunderPublicId UNIQUEIDENTIFIER,
         ContentVersion INT, PublicationStatus TINYINT, RowVersion BINARY(8), WasReplay BIT);

    INSERT INTO @Result EXEC dbo.FundingPlatform_usp_Funder_Create
        @AdminUserPublicId = @Owner, @Slug = @Slug, @Name = @Slug,
        @WebsiteUrl = N'https://example.invalid/funder', @CountryId = 840,
        @IdempotencyKeyHash = @Key, @RequestHash = @Hash, @OwnerWorkspace = 1;
    DECLARE @Funder UNIQUEIDENTIFIER = (SELECT FunderPublicId FROM @Result);
    DECLARE @Version BINARY(8) = (SELECT RowVersion FROM @Result);
    IF NOT EXISTS (SELECT 1 FROM @Result WHERE Succeeded = 1 AND PublicationStatus = 0)
       OR NOT EXISTS (SELECT 1 FROM dbo.FundingPlatform_Funders WHERE PublicId = @Funder AND CountryId = 840)
        THROW 55585, N'Funder creation did not preserve the selected United States country.', 1;

    SET @Key = HASHBYTES('SHA2_256', @Slug + N'-update');
    DELETE FROM @Result;
    INSERT INTO @Result EXEC dbo.FundingPlatform_usp_Funder_Update
        @AdminUserPublicId = @Owner, @FunderPublicId = @Funder, @ExpectedRowVersion = @Version,
        @Name = @Slug, @Description = N'Country selection update', @WebsiteUrl = N'https://example.invalid/funder',
        @CountryId = 392, @IdempotencyKeyHash = @Key, @RequestHash = @Hash, @OwnerWorkspace = 1;
    IF NOT EXISTS (SELECT 1 FROM @Result WHERE Succeeded = 1 AND PublicationStatus = 0 AND ContentVersion = 2)
       OR NOT EXISTS (SELECT 1 FROM dbo.FundingPlatform_Funders WHERE PublicId = @Funder AND CountryId = 392)
        THROW 55586, N'Funder update did not preserve Japan or bypassed editorial draft status.', 1;

    IF @InitialTransactionCount = 0 ROLLBACK TRANSACTION;
    ELSE ROLLBACK TRANSACTION FP_Smoke048;
END TRY
BEGIN CATCH
    IF @InitialTransactionCount = 0 AND XACT_STATE() <> 0 ROLLBACK TRANSACTION;
    ELSE IF @InitialTransactionCount > 0 AND XACT_STATE() = 1 ROLLBACK TRANSACTION FP_Smoke048;
    THROW;
END CATCH;
